### ISSUE TITLE
.xsession-errors and warnings

### ISSUE THREAD

**Issue by asolopovas** [blueman-project/blueman#1214]
blueman: 2.1.2

Distribution:Linux main-linux-host 5.6.3-arch1-1 #1 SMP PREEMPT Wed, 08 Apr 2020 07:47:16 +0000 x86_64 GNU/Linux
Desktop environment: i3 + polybar

Hi I am getting the following error when running blueman-applet  in my `~/.xsession-errors` what could be the cause of that?
```
blueman-applet 20.23.12 WARNING  PluginManager:147 __load_plugin: Not loading DhcpClient because its conflict has higher priority
Attribute Qt::AA_ShareOpenGLContexts must be set before QCoreApplication is created.
blueman-applet 20.23.12 WARNING  PluginManager:147 __load_plugin: Not loading PPPSupport because its conflict has higher priority
blueman-applet 20.23.12 WARNING  TransferService:189 _make_share_path: Failed to get Download dir from XDG

(blueman-tray:18507): Gdk-CRITICAL **: 20:23:12.625: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
qrc:/QML/DebugMenu.qml:262: TypeError: Cannot call method 'isWasabiEnabled' of undefined
qrc:/QML/DebugMenu.qml:289: TypeError: Cannot call method 'isSearchInCommunitiesForceEnabled' of undefined
qrc:/QML/DebugMenu.qml:296: TypeError: Cannot call method 'isOOABURISpamCheckerForceEnabled' of undefined
qrc:/QML/DebugMenu.qml:304: TypeError: Cannot call method 'isRateCallQualityForceEnabled' of undefined
[18850:18850:0409/202326.792159:ERROR:browser_switcher_service.cc(238)] XXX Init()
[18850:18850:0409/202327.440473:ERROR:bookmark_app_install_finalizer.cc(291)] Installed extension was disabled: 1
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/blueman/main/indicators/GtkStatusIcon.py", line 19, in <lambda>
    gtk_item.connect('activate', lambda _, idx=index: activate(idx))
  File "/usr/lib/python3.8/site-packages/blueman/main/Tray.py", line 37, in _activate_menu_item
    return AppletService().ActivateMenuItem('(ai)', indexes)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gio.py", line 351, in __call__
    result = self.dbus_proxy.call_sync(self.method_name, arg_variant,
gi.repository.GLib.Error: g-io-error-quark: Timeout was reached (24)
```

**Comment by cschramm** [comment]
Hi, do you see any issues with the tray icon? Does the exception happen on start? Are you able to replicate it somehow?
