### ISSUE TITLE
dbus failure in fedora 21

### ISSUE THREAD

**Issue by raveit65** [blueman-project/blueman#161]
Hi,
first i wanna say a big thank you for re-starting development.
I wanna bring back blueman in fedora.
Unfortunately, the blueman-applet doesnt start in fedora 21, from a terminal:

```
[rave@mother ~]$ blueman-applet 

** (blueman-applet:1581): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Loading configuration plugins
blueman-applet version 1.99.alpha1 starting
Stale PID, overwriting
Using GConf config backend
_________
Load (/usr/lib/python2.7/site-packages/blueman/main/PluginManager.py:54)
['TransferService', 'NMPANSupport', 'RecentConns', 'DhcpClient', 'SerialManager', 'ExitItem', 'AppIndicator', 'StandardItems', 'DBusService', 'Menu', 'StatusIcon', 'NetUsage', 'PPPSupport', 'ShowConnected', 'AuthAgent', 'Networking', 'NMDUNSupport', 'PowerManager', 'DiscvManager', 'KillSwitch', 'Headset'] 
Using GConf config backend
_________
Load (/usr/lib/python2.7/site-packages/blueman/main/PluginManager.py:54)
Unable to load plugin module AppIndicator
cannot import name AppIndicator3 
_________
get_interface_version (/usr/lib/python2.7/site-packages/blueman/bluez/BlueZInterface.py:8)
Detected BlueZ 5 
_________
__load_plugin (/usr/lib/python2.7/site-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.StatusIcon.StatusIcon'> 
_________
__load_plugin (/usr/lib/python2.7/site-packages/blueman/main/PluginManager.py:127)
loading <class 'blueman.plugins.applet.DBusService.DBusService'> 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/blueman/plugins/BasePlugin.py", line 65, in _load
    self.on_load(parent)
  File "/usr/lib/python2.7/site-packages/blueman/plugins/applet/DBusService.py", line 35, in on_load
    self.add_dbus_method(self.ServiceProxy, in_signature="sosas", async_callbacks=("ok", "err"))
  File "/usr/lib/python2.7/site-packages/blueman/plugins/AppletPlugin.py", line 77, in add_dbus_method
    self.Applet.DbusSvc.add_method(func, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/blueman/main/DbusService.py", line 62, in add_method
    if not dbus_interface in self._dbus_class_table[self.__class__.__module__+"."+self.__class__.__name__]:
AttributeError: 'DbusService' object has no attribute '_dbus_class_table'
_________
__load_plugin (/usr/lib/python2.7/site-packages/blueman/main/PluginManager.py:127)
Failed to load DBusService
'DbusService' object has no attribute '_dbus_class_table' 
```

Note, this is a build from latest git snapshot from 2014-12-26
If you need further infos let me know, ie. gdb output.
Good news, it runs well in fedora 20 :)

Ps: why there is no sendto plugin for caja and nemo?
I'm fedora mate package maintainer + mate upstream, and the new fedora bluemen maintainer maintains cinnamon in fedora ;)

**Comment by cschramm** [comment]
I've prepared some changes concerning the dbus service of blueman: https://github.com/blueman-project/blueman/pull/170

Instead of modifying the table, we now re-run `dbus.service.InterfaceType.__init__` after adding or removing service methods at the class level, so the name and structure of the internal table does not matter anymore. I haven't tested it, but it should work fine with the dangling dbus-python patch applied.
