### ISSUE TITLE
Playstation Move Motion Controllers Wont Stay Connected

### ISSUE THREAD

**Issue by jeottav** [blueman-project/blueman#169]
Sorry for lack of info.

blueman: 1.23
bluez: 4.101-0ubuntu20
distro: lubuntu
desktop environment: LXDE

**Comment by cschramm** [comment]
https://github.com/blueman-project/blueman/wiki/Troubleshooting

**Comment by jeottav** [comment]
__init__ (/usr/lib/python2.7/dist-packages/blueman/main/Device.py:16)
caching initial properties 
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/blueman/plugins/applet/SerialManager.py", line 70, in on_device_property_changed
    d = Device(path)
  File "/usr/lib/python2.7/dist-packages/blueman/main/Device.py", line 39, in __init__
    self.Properties = self.Device.GetProperties()
  File "/usr/lib/python2.7/dist-packages/blueman/bluez/utils.py", line 28, in warp
    raise errors.parse_dbus_error(exception)
DBusException: org.freedesktop.DBus.Error.UnknownObject: Method "GetProperties" with signature "" on interface "org.bluez.Device" doesn't exist

**Comment by cschramm** [comment]
That exception is out of context and most probably not the cause of your problem. Please try to produce some meaningful output. You can try the script from #173 to describe, what you're doing and what's happening while producing the log ("Connect controller", "Controller just disconnected", ...).
