### ISSUE TITLE
'No such interface 'org.bluez.Battery1' errors

### ISSUE THREAD

**Issue by kuraga** [blueman-project/blueman#1708]
blueman: 2.2.3
BlueZ: 5.64
Distribution: Calculate Linux
Desktop environment: XFCE 4.16

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

I have errors in log such like this:
```
blueman-manager 19.37.31 ERROR    ManagerDeviceList:324 row_setup_event: org.freedesktop.DBus.Error.InvalidArgs No such interface 'org.bluez.Battery1'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/blueman/bluez/Base.py", line 92, in get
    prop = self.call_sync(
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: No such interface 'org.bluez.Battery1' (16)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 322, in row_setup_event
    self.row_update_event(tree_iter, "Connected", device["Connected"])
  File "/usr/lib/python3.9/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 397, in row_update_event
    self._monitor_power_levels(tree_iter, self.get(tree_iter, "device")["device"])
  File "/usr/lib/python3.9/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 343, in _monitor_power_levels
    self._update_power_levels(tree_iter, device, cinfo)
  File "/usr/lib/python3.9/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 408, in _update_power_levels
    bars["battery"] = Battery(obj_path=device.get_object_path())["Percentage"]
  File "/usr/lib/python3.9/site-packages/blueman/bluez/Base.py", line 135, in __getitem__
    return self.get(key)
  File "/usr/lib/python3.9/site-packages/blueman/bluez/Base.py", line 106, in get
    raise parse_dbus_error(e)
blueman.bluez.errors.BluezDBusException: org.freedesktop.DBus.Error.InvalidArgs No such interface 'org.bluez.Battery1'
```

Is it a known issue? Thanks.

**Comment by kuraga** [comment]
blueman: 2.2.3
BlueZ: 5.64
Distribution: Calculate Linux
Desktop environment: XFCE 4.16

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

I have errors in log such like this:
```
blueman-manager 19.37.31 ERROR    ManagerDeviceList:324 row_setup_event: org.freedesktop.DBus.Error.InvalidArgs No such interface 'org.bluez.Battery1'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/blueman/bluez/Base.py", line 92, in get
    prop = self.call_sync(
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: No such interface 'org.bluez.Battery1' (16)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 322, in row_setup_event
    self.row_update_event(tree_iter, "Connected", device["Connected"])
  File "/usr/lib/python3.9/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 397, in row_update_event
    self._monitor_power_levels(tree_iter, self.get(tree_iter, "device")["device"])
  File "/usr/lib/python3.9/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 343, in _monitor_power_levels
    self._update_power_levels(tree_iter, device, cinfo)
  File "/usr/lib/python3.9/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 408, in _update_power_levels
    bars["battery"] = Battery(obj_path=device.get_object_path())["Percentage"]
  File "/usr/lib/python3.9/site-packages/blueman/bluez/Base.py", line 135, in __getitem__
    return self.get(key)
  File "/usr/lib/python3.9/site-packages/blueman/bluez/Base.py", line 106, in get
    raise parse_dbus_error(e)
blueman.bluez.errors.BluezDBusException: org.freedesktop.DBus.Error.InvalidArgs No such interface 'org.bluez.Battery1'
```

Is it a known issue? Thanks.

**Comment by cschramm** [comment]
Not known to me.

The missing battery interface is usually available if services are resolved and the device does have a battery service. Otherwise we do not try to use it.

Could you check if the device does have the interface in the BlueZ D-Bus API, e.g. with `d-feet`? I think `bluetoothctl info` for the device should also show the percentage if the interface is present.

**Comment by kuraga** [comment]
Seems like `Battery1`, etc. isn't exposed on my headsets...

So, 1) this is an underlying issue,
2) it'd be good to handle the exception?

**Comment by cschramm** [comment]
Anything interesting in bluetoothd logs regarding the device? :thinking:

**Comment by infirit** [comment]
afaik bluez only exposes `Battery1` for LE devices, it doesn't do any AT commands. But yeah would like to see what `bluetoothd` has in it's log

**Comment by kuraga** [comment]
Sorry I think I would't debug underlying things... Device support isn't brilliant, it's known.

**Comment by kuraga** [comment]
@cschramm , but what about exception handling?

**Comment by cschramm** [comment]
The situation is completely unexpected and we do not know any background, so raising the error seems like the proper handling.

**Comment by kuraga** [comment]
Ok.

P.S. https://github.com/bluez/bluez/issues/188#issuecomment-1115298948

**Comment by MarijnS95** [comment]
> afaik bluez only exposes `Battery1` for LE devices, it doesn't do any AT commands. But yeah would like to see what `bluetoothd` has in it's log

PulseAudio will indirectly provide the result from AT commands through BlueZ's _experimental_ `BatteryProvider1` API now/soon :)
