### ISSUE TITLE
Blueman (applet) not starting with timeout error

### ISSUE THREAD

**Issue by bottom-bracket** [blueman-project/blueman#1923]
blueman: community 2.3.4-1
BlueZ: 5.65
Distribution: Manjaro Linux (Arch)
Desktop environment: i3

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

When starting `blueman-applet` it fails with the following error:
```
Traceback (most recent call last):
  File "/usr/bin/blueman-applet", line 40, in <module>
    app = BluemanApplet()
  File "/usr/lib/python3.10/site-packages/blueman/main/Applet.py", line 33, in __init__
    self.Manager = Manager()
  File "/usr/lib/python3.10/site-packages/blueman/gobject.py", line 11, in __call__
    cls._instance = super().__call__(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/blueman/bluez/Manager.py", line 30, in __init__
    self._object_manager = Gio.DBusObjectManagerClient.new_for_bus_sync(
gi.repository.GLib.GError: g-io-error-quark: Timeout was reached (24)
```
I did try to reinstall all bluetooth related packages, updated everything, restarted and tested different kernels but without success. Since this is not the first time I experience this error (in the past I waited a few weeks until the next major updates and somehow it would work again) I decided to open an issue here. Also I did not find much about this error elsewhere :/

**Comment by bottom-bracket** [comment]
Ok I'm not sure if this is a stable issue. Suddenly disappeared.
