### ISSUE TITLE
Message recipient disconnected from message bus without replying (4)

### ISSUE THREAD

**Issue by rodrigolitzius** [blueman-project/blueman#2072]
blueman: 2.3.5-2
BlueZ: 5.66-1
Distribution: Archlinux
Window Manager: i3

> What i do to reproduce the bug:
>
`$ blueman-manager`
After a bit of waiting and no window, it outputs **_Blueman applet needs to be running_**

Then i run blueman-applet. This is the result:
`blueman-applet 02.35.22 WARNING  TransferService:213 _make_share_path: Failed to get Download dir from XDG
blueman-applet 02.35.22 WARNING  PluginManager:151 __load_plugin: Not loading DhcpClient because its conflict has higher priority
blueman-applet 02.35.22 WARNING  PluginManager:151 __load_plugin: Not loading PPPSupport because its conflict has higher priority`

Left-clicking the applet outputs this:
`Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/blueman/main/DBusProxies.py", line 52, in call_finish
    proxy.call_finish(resp)
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying (4)`

This time, running _blueman-manager_ does work and the window shows up.
When i try searching for devices, this same error occurs multiple times:
`Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 648, in _set_cell_data
    surface = self.make_device_icon(row["icon_info"], row["paired"], row["trusted"], row["blocked"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 265, in make_device_icon
    target = icon_info.load_surface(window)
             ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'load_surface'`

When i try connecting to my bluetooth earphones for the first time it says it connected, but this error shows up:
`blueman-manager 02.43.34 WARNING  ManagerDeviceMenu:145 fail      : fail g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.Failed: blueman.bluez.errors.DBusFailedError:  br-connection-page-timeout`

on the second try it works and fine. And also clicking the applet with the window open just crashes the it.

Note: It was working before. It broke suddenly

* [ x ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

[--loglevel debug](https://pastebin.com/zKFLMc0q)

**Comment by rodrigolitzius** [comment]
It fixed itself. Should i close the issue?
