### ISSUE TITLE
Exception when restarting bluetoothd

### ISSUE THREAD

**Issue by davidgfnet** [blueman-project/blueman#209]
Hi,
Seems that if I restart bluetoothd (kill+exec) it will throw this exception:
_________
on_dbus_name_owner_change (/usr/bin/blueman-applet:89)
org.bluez owner changed to  
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 65, in signal_cb
    callback(new_owner)
  File "/usr/bin/blueman-applet", line 92, in on_dbus_name_owner_change
    self.manager_deinit()
  File "/usr/bin/blueman-applet", line 85, in manager_deinit
    self.Signals.DisconnectAll()
  File "/usr/lib/python2.7/site-packages/blueman/main/SignalTracker.py", line 74, in DisconnectAll
    obj.unhandle_signal(*args)
  File "/usr/lib/python2.7/site-packages/blueman/bluez/PropertiesBlueZInterface.py", line 69, in unhandle_signal
    raise Exception('Unknown signal: %s' % signal)
Exception: Unknown signal: AdapterRemoved

I dont know whether that is expected. Seems that my dongle crashes a lot but it's something HW specific and not a blueman problem.

**Comment by cschramm** [comment]
I fixed that in #210, but did not have the time to try it myself.
