### ISSUE TITLE
Failed to apply network settings you might not be able to connect to the Bluetooth network via this machine

### ISSUE THREAD

**Issue by mafanpamafan** [blueman-project/blueman#2208]
blueman:2.0.8-1+deb10u1
BlueZ: 5.50-1.2~deb10u2 
Distribution:Debian10 
Desktop environment:LXDE

This situation is not 100% of the occurrence, there is a probability of occurrence every time the boot.
![c7ce6ab6aaa437cc9bcd511b5cb7cb4](https://github.com/blueman-project/blueman/assets/143488967/d0cd27c8-962b-4d40-9e7e-23e2805ea1e6)

I've looked at /usr/share/polkit-1/rules.d/blueman.rules and it looks like this:
```
// Allow users in sudo or netdev group to use blueman feature requiring root without authentication
polkit.addRule(function(action, subject) {
    if ((action.id == "org.blueman.network.setup" ||
         action.id == "org.blueman.dhcp.client" ||
         action.id == "org.blueman.rfkill.setstate" ||
         action.id == "org.blueman.pppd.pppconnect") &&
        subject.local && subject.active &&
        (subject.isInGroup("sudo") || subject.isInGroup("netdev"))) {
        return polkit.Result.YES;
    }
});
```

Then I've checked my groups already in sudo and netdev:
![image](https://github.com/blueman-project/blueman/assets/143488967/a1c6b5f3-7ef6-41e7-aca9-356117175d98)

Any idea about this situation?

**Comment by mafanpamafan** [comment]
Yeah,thanks for your reply.Unfortunately,I have to work on these current versions.
After trying your suggestion, I did get the same prompt again, and the blueman-applet prints as follows：
`(blueman-applet:1347): dbind-WARNING **: 01:42:10.905: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
blueman-applet version 2.0.8 starting
_________
Load (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:60)
['NMPANSupport', 'DiscvManager', 'RecentConns', 'StatusIcon', 'SerialManager', 'NMDUNSupport', 'TransferService', 'ExitItem', 'DBusService', 'AppIndicator', 'DhcpClient', 'KillSwitch', 'PowerManager', 'Networking', 'AuthAgent', 'Menu', 'ShowConnected', 'NetUsage', 'PPPSupport', 'StandardItems', 'GameControllerWakelock', 'Headset']
_________
Load (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:60)
Unable to load plugin module NMPANSupport
NM python bindings not found.
_________
Load (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:60)
Unable to load plugin module NMDUNSupport
NM python bindings not found.
_________
get_interface_version (/usr/lib/python3/dist-packages/blueman/bluez/BlueZInterface.py:13)
Detected BlueZ 5
/usr/lib/python3/dist-packages/blueman/plugins/applet/AppIndicator.py:8: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as girAppIndicator
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.StatusIcon.StatusIcon'>
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.Menu.Menu'>
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.DiscvManager.DiscvManager'>
_________
update_menuitems (/usr/lib/python3/dist-packages/blueman/plugins/applet/DiscvManager.py:123)
warning: Adapter is None
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.RecentConns.RecentConns'>
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.SerialManager.SerialManager'>
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.TransferService.TransferService'>
_________
get_interface_version (/usr/lib/python3/dist-packages/blueman/bluez/obex/Base.py:20)
Detected BlueZ integrated obexd
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.ExitItem.ExitItem'>
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.DBusService.DBusService'>
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.AppIndicator.AppIndicator'>
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.DhcpClient.DhcpClient'>
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.PowerManager.PowerManager'>
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.KillSwitch.KillSwitch'>
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.Networking.Networking'>
_________
load_nap_settings (/usr/lib/python3/dist-packages/blueman/plugins/applet/Networking.py:36)
Loading NAP settings
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.AuthAgent.AuthAgent'>
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.ShowConnected.ShowConnected'>
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.PPPSupport.PPPSupport'>
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.StandardItems.StandardItems'>
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.GameControllerWakelock.GameControllerWakelock'>
_________
__load_plugin (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.Headset.Headset'>
_________
io_event (/usr/lib/python3/dist-packages/blueman/plugins/applet/KillSwitch.py:71)
killswitch registered 0
_________
io_event (/usr/lib/python3/dist-packages/blueman/plugins/applet/KillSwitch.py:71)
State: True
_________
UpdatePowerState (/usr/lib/python3/dist-packages/blueman/plugins/applet/PowerManager.py:159)
off False
foff False
on True
current state True
new state True
_________
io_event (/usr/lib/python3/dist-packages/blueman/plugins/applet/KillSwitch.py:71)
killswitch registered 3
_________
io_event (/usr/lib/python3/dist-packages/blueman/plugins/applet/KillSwitch.py:71)
State: True
_________
UpdatePowerState (/usr/lib/python3/dist-packages/blueman/plugins/applet/PowerManager.py:159)
off False
foff False
on True
current state True
new state True
_________
_on_obex_owner_changed (/usr/lib/python3/dist-packages/blueman/plugins/applet/TransferService.py:172)
obex owner changed: :1.4
_________
on_dbus_name_owner_change (/usr/bin/blueman-applet:95)
org.bluez owner changed to :1.17
_________
initialize (/usr/lib/python3/dist-packages/blueman/plugins/applet/RecentConns.py:144)
rebuilding menu
_________
set_nap (/usr/lib/python3/dist-packages/blueman/plugins/applet/Networking.py:65)
set nap False
_________
Run (/usr/lib/python3/dist-packages/blueman/main/PluginManager.py:208)
Function on_manager_state_changed on Networking Failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/blueman/main/PluginManager.py", line 212, in Run
    ret = getattr(inst, function)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/blueman/plugins/applet/Networking.py", line 34, in on_manager_state_changed
    self.update_status()
  File "/usr/lib/python3/dist-packages/blueman/plugins/applet/Networking.py", line 59, in update_status
    self.set_nap(self.Config["nap-enable"])
  File "/usr/lib/python3/dist-packages/blueman/plugins/applet/Networking.py", line 74, in set_nap
    s.unregister("nap")
  File "/usr/lib/python3/dist-packages/blueman/bluez/errors.py", line 148, in warp
    raise parse_dbus_error(exception)
  File "/usr/lib/python3/dist-packages/blueman/bluez/errors.py", line 146, in warp
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/blueman/bluez/NetworkServer.py", line 26, in unregister
    self.get_interface().Unregister(uuid)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method "Unregister" with signature "s" on interface "org.bluez.NetworkServer1" doesn't exist

_________
register_agent (/usr/lib/python3/dist-packages/blueman/plugins/applet/AuthAgent.py:63)
Registering agent
_________
enumerate_connections (/usr/lib/python3/dist-packages/blueman/plugins/applet/ShowConnected.py:53)
Found 0 existing connections
_________
on_registered (/usr/lib/python3/dist-packages/blueman/bluez/obex/AgentManager.py:18)
/org/blueman/obex_agent

(blueman-applet:1347): Gdk-CRITICAL **: 01:42:12.789: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
_________
RequestPowerState (/usr/lib/python3/dist-packages/blueman/plugins/applet/PowerManager.py:131)
Requesting True
_________
on_power_state_change_requested (/usr/lib/python3/dist-packages/blueman/plugins/applet/KillSwitch.py:118)
True
_________
UpdatePowerState (/usr/lib/python3/dist-packages/blueman/plugins/applet/PowerManager.py:159)
off False
foff False
on True
current state True
new state True
_________
timeout (/usr/lib/python3/dist-packages/blueman/plugins/applet/PowerManager.py:126)
Timeout reached while setting power state
_________
UpdatePowerState (/usr/lib/python3/dist-packages/blueman/plugins/applet/PowerManager.py:159)
off False
foff False
on True
current state True
new state True`

But the exception describtion is different?
![5c46b90d78f15d67820f8ce80c8efd5](https://github.com/blueman-project/blueman/assets/143488967/ee972b4e-93ac-4d00-8253-299e763d2563)
