### ISSUE TITLE
GConf plugin throws exception on first use

### ISSUE THREAD

**Issue by defeo** [blueman-project/blueman#252]
When using the `Gconf.py` plugin, if the directory `.gconf/apps/blueman` is missing, blueman fails with the following exception

```
Loading configuration plugins
blueman-applet version 1.99.alpha1 starting
Stale PID, overwriting
Using GConf config backend
Using GConf config backend
Using GConf config backend
Traceback (most recent call last):
  File "/usr/bin/blueman-applet", line 110, in <module>
    BluemanApplet()
  File "/usr/bin/blueman-applet", line 53, in __init__
    self.Plugins.Load()
  File "/usr/lib/python2.7/dist-packages/blueman/main/PluginManager.py", line 115, in Load
    if (cls.__autoload__ or cls.__name__ in c) and not (cls.__unloadable__ and "!" + cls.__name__ in c):
TypeError: argument of type 'NoneType' is not iterable
```

After the first failure, the directory is created, and blueman wil start normally thereafter. But this is specially annoying on live systems.

**Comment by cschramm** [comment]
We're not using GConf anymore. :smiley: alpha2 uses gsettings.
