### ISSUE TITLE
error when trying to connect a bluetooth printer

### ISSUE THREAD

**Issue by amias69** [blueman-project/blueman#2558]
blueman: 2.4.3
BlueZ: 5.79-1
Distribution: Endeavour OS
Desktop environment: Budgie

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Ha fallado la conexión: File "/usr/lib/python3.12/site-packages/blueman/main/DbusService.py", line 154, in _handle_method_call
    method(*(args + (ok, lambda exception: self._return_dbus_error(invocation, exception))))
  File "/usr/lib/python3.12/site-packages/blueman/plugins/applet/DBusService.py", line 93, in connect_service
    service.connect(reply_handler=lambda port: ok(), error_handler=err)
  File "/usr/lib/python3.12/site-packages/blueman/services/meta/SerialService.py", line 104, in connect
    Mechanism().OpenRFCOMM('(d)', port_id)
  File "/usr/lib/python3.12/site-packages/gi/overrides/Gio.py", line 374, in __call__
    result = self.dbus_proxy.call_sync(self.method_name, arg_variant,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.Failed: Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/blueman/main/DbusService.py", line 156, in _handle_method_call
    ok(method(*args))
       ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/blueman/plugins/mechanism/Rfcomm.py", line 14, in _open_rfcomm
    subprocess.Popen([RFCOMM_WATCHER_PATH, f"/dev/rfcomm{port_id:d}"])
                                                        ^^^^^^^^^^^
ValueError: Unknown format code 'd' for object of type 'float'
 (0)

**Comment by cschramm** [comment]
This is fixed in #2492 and scheduled for a 2.4.4 patch release
