### ISSUE TITLE
NetConf: with stale lock file and changing IP self.pid may be None

### ISSUE THREAD

**Issue by infirit** [blueman-project/blueman#399]
https://github.com/blueman-project/blueman/issues/397#issuecomment-160154347

```python
org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/dist-packages/blueman/main/DbusService.py", line 36, in wrapper
    return method(*args[1:], **kwargs)
  File "/usr/lib/python2.7/dist-packages/blueman/plugins/mechanism/Network.py", line 57, in EnableNetwork
    nc.apply_settings()
  File "/usr/lib/python2.7/dist-packages/blueman/main/NetConf.py", line 304, in apply_settings
    self.dhcp_handler.do_apply()
  File "/usr/lib/python2.7/dist-packages/blueman/main/NetConf.py", line 35, in do_apply
    self.do_remove()
  File "/usr/lib/python2.7/dist-packages/blueman/main/NetConf.py", line 65, in do_remove
    os.kill(self.pid, signal.SIGTERM)
TypeError: an integer is required
```

The problem is that if the lock file exist and the user modified the ip address we try to kill the dhcphandler with do_remove that calls os.kill(self.pid). But self.pid at that stage is None and we run into #397 (comment). And the only place we unlock is in do_remove...

https://github.com/blueman-project/blueman/issues/397#issuecomment-160390877
```The best solution would probably be to store the PID in the lockfile to a) have it persisted and b) be able to check if it's actually still running or not. We have such a logic in Functions.check_single_instance.```

easiest to reproduce is to remove ``/var/lib/blueman/network.state`` and make sure the lock file is still there.

Also similar to this problem, if the dhcphandler dies for some reason we may try to kill a non existing process. We should probably handle this, see below.
```python
org.freedesktop.DBus.Python.ProcessLookupError: Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib64/python3.4/site-packages/blueman/main/DbusService.py", line 36, in wrapper
    return method(*args[1:], **kwargs)
  File "/usr/lib64/python3.4/site-packages/blueman/plugins/mechanism/Network.py", line 57, in EnableNetwork
    nc.apply_settings()
  File "/usr/lib64/python3.4/site-packages/blueman/main/NetConf.py", line 304, in apply_settings
    self.dhcp_handler.do_apply()
  File "/usr/lib64/python3.4/site-packages/blueman/main/NetConf.py", line 35, in do_apply
    self.do_remove()
  File "/usr/lib64/python3.4/site-packages/blueman/main/NetConf.py", line 65, in do_remove
    os.kill(self.pid, signal.SIGTERM)
ProcessLookupError: [Errno 3] No such process
```

**Comment by infirit** [comment]
https://github.com/blueman-project/blueman/pull/401
