### ISSUE TITLE
blueman-manager: Fix exceptions on bluetooth restart

### ISSUE THREAD

**Issue by infirit** [blueman-project/blueman#550]
Issue to keep track of this so we don't forget.

This is from master but 2.0.4 also has exceptions which we could look at later perhaps. It is low priority as blueman-manager closes anyway but it will probably show up on in crash reporting tools and annoy maintainers :smile: .

```
device_remove_event (/usr/lib64/python3.5/site-packages/blueman/gui/DeviceList.py:198)
<Device.Device object at 0x7f10a1b450d8 (blueman+bluez+Device+Device at 0x240b820)> 
_________
device_remove_event (/usr/lib64/python3.5/site-packages/blueman/gui/DeviceList.py:198)
<Device.Device object at 0x7f10a1b450d8 (blueman+bluez+Device+Device at 0x240b820)> 
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 202, in on_finished
    super(ManagerDeviceList, self).device_remove_event(device, tree_iter)
  File "/usr/lib64/python3.5/site-packages/blueman/gui/DeviceList.py", line 206, in device_remove_event
    sig = self.__signals.pop(device.get_object_path())
KeyError: '/org/bluez/hci0/dev_6C_83_36_B9_C6_D6'
_________
device_remove_event (/usr/lib64/python3.5/site-packages/blueman/gui/DeviceList.py:198)
<Device.Device object at 0x7f10a1b40c60 (blueman+bluez+Device+Device at 0x240b6c0)> 
_________
device_remove_event (/usr/lib64/python3.5/site-packages/blueman/gui/DeviceList.py:198)
<Device.Device object at 0x7f10a1b40c60 (blueman+bluez+Device+Device at 0x240b6c0)> 
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 202, in on_finished
    super(ManagerDeviceList, self).device_remove_event(device, tree_iter)
  File "/usr/lib64/python3.5/site-packages/blueman/gui/DeviceList.py", line 206, in device_remove_event
    sig = self.__signals.pop(device.get_object_path())
KeyError: '/org/bluez/hci0/dev_00_07_61_48_7A_2C'
_________
device_remove_event (/usr/lib64/python3.5/site-packages/blueman/gui/DeviceList.py:198)
<Device.Device object at 0x7f10a1b40f30 (blueman+bluez+Device+Device at 0x240b520)> 
_________
device_remove_event (/usr/lib64/python3.5/site-packages/blueman/gui/DeviceList.py:198)
<Device.Device object at 0x7f10a1b40f30 (blueman+bluez+Device+Device at 0x240b520)> 
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 202, in on_finished
    super(ManagerDeviceList, self).device_remove_event(device, tree_iter)
  File "/usr/lib64/python3.5/site-packages/blueman/gui/DeviceList.py", line 206, in device_remove_event
    sig = self.__signals.pop(device.get_object_path())
KeyError: '/org/bluez/hci0/dev_00_1F_20_3A_89_89'
_________
device_remove_event (/usr/lib64/python3.5/site-packages/blueman/gui/DeviceList.py:198)
<Device.Device object at 0x7f10a1b45288 (blueman+bluez+Device+Device at 0x240c420)> 
_________
device_remove_event (/usr/lib64/python3.5/site-packages/blueman/gui/DeviceList.py:198)
<Device.Device object at 0x7f10a1b45288 (blueman+bluez+Device+Device at 0x240c420)> 
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 202, in on_finished
    super(ManagerDeviceList, self).device_remove_event(device, tree_iter)
  File "/usr/lib64/python3.5/site-packages/blueman/gui/DeviceList.py", line 206, in device_remove_event
    sig = self.__signals.pop(device.get_object_path())
KeyError: '/org/bluez/hci0/dev_40_F4_07_CB_E4_D7'
_________
device_remove_event (/usr/lib64/python3.5/site-packages/blueman/gui/DeviceList.py:198)
<Device.Device object at 0x7f10a1b451b0 (blueman+bluez+Device+Device at 0x240b9a0)> 
_________
device_remove_event (/usr/lib64/python3.5/site-packages/blueman/gui/DeviceList.py:198)
<Device.Device object at 0x7f10a1b451b0 (blueman+bluez+Device+Device at 0x240b9a0)> 
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 202, in on_finished
    super(ManagerDeviceList, self).device_remove_event(device, tree_iter)
  File "/usr/lib64/python3.5/site-packages/blueman/gui/DeviceList.py", line 206, in device_remove_event
    sig = self.__signals.pop(device.get_object_path())
KeyError: '/org/bluez/hci0/dev_30_75_12_04_F7_2F'
_________
update (/usr/lib64/python3.5/site-packages/blueman/gui/DeviceList.py:139)
stopping monitor (row does not exist) 
```

**Comment by infirit** [comment]
Got them sorted for master.
