### ISSUE TITLE
Error when gsettings has last adapter set to none existing one

### ISSUE THREAD

**Issue by infirit** [blueman-project/blueman#590]
This is probably a bug with the recent changes so self assigning. Too tired now.
```
_________
do_g_properties_changed (/usr/lib64/python2.7/site-packages/blueman/bluez/Base.py:81)
/org/bluez/hci0 UUIDs ['00001112-0000-1000-8000-00805f9b34fb', '00001801-0000-1000-8000-00805f9b34fb', '0000110e-0000-1000-8000-00805f9b34fb', '00001106-0000-1000-8000-00805f9b34fb', '00001800-0000-1000-8000-00805f9b34fb', '00001105-0000-1000-8000-00805f9b34fb', '00001200-0000-1000-8000-00805f9b34fb', '0000110c-0000-1000-8000-00805f9b34fb', '00001104-0000-1000-8000-00805f9b34fb', '0000110a-0000-1000-8000-00805f9b34fb', '0000110b-0000-1000-8000-00805f9b34fb', '00005005-0000-1000-8000-0002ee000001', '00001116-0000-1000-8000-00805f9b34fb', '00001133-0000-1000-8000-00805f9b34fb', '0000112f-0000-1000-8000-00805f9b34fb', '00001132-0000-1000-8000-00805f9b34fb'] 
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/blueman/main/Manager.py", line 133, in on_dbus_name_appeared
    self.List = ManagerDeviceList(adapter=self.Config["last-adapter"], inst=self)
  File "/usr/lib64/python2.7/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 62, in __init__
    super(ManagerDeviceList, self).__init__(adapter, data)
  File "/usr/lib64/python2.7/site-packages/blueman/gui/DeviceList.py", line 104, in __init__
    self.SetAdapter(adapter)
  File "/usr/lib64/python2.7/site-packages/blueman/gui/DeviceList.py", line 240, in SetAdapter
    self.Adapter.connect_signal('property-changed', self._on_property_changed)
AttributeError: 'NoneType' object has no attribute 'connect_signal'
```

**Comment by infirit** [comment]
Not a bug I introduced recently, it has been there for a while. I can fix this in two ways.

 1. Change ``Manager.get_adapter`` to return something even when we can not match with the pattern. I don't like this, if a pattern is provided we should only ever return if we have a match, if not return ``None``.
 2. Check in ``DeviceList.SetAdapter`` if ``Manager.get_adapter`` returned ``None`` and retry without pattern.

Below both approaches in a single diff. I'll push the second approach unless there are objections raised in the next couple of days.

```diff
diff --git a/blueman/bluez/Manager.py b/blueman/bluez/Manager.py
index 2efc1d4..9b43d6d 100644
--- a/blueman/bluez/Manager.py
+++ b/blueman/bluez/Manager.py
@@ -79,15 +79,20 @@ class Manager(GObject.GObject):
 
     def get_adapter(self, pattern=None):
         adapters = self.get_adapters()
+        if len(adapters) == 0:
+            return None
+
         if pattern is None:
-            if len(adapters):
-                return adapters[0]
+            return adapters[0]
         else:
             for adapter in adapters:
                 path = adapter.get_object_path()
                 if path.endswith(pattern) or adapter.get_properties()['Address'] == pattern:
                     return adapter
 
+        # If the patern is incorrect return the first adapter
+        return adapters[0]
+
     def get_devices(self, adapter_path='/'):
         paths = []
         for obj_proxy in self._object_manager.get_objects():
diff --git a/blueman/gui/DeviceList.py b/blueman/gui/DeviceList.py
index 74589ac..11c1fc1 100644
--- a/blueman/gui/DeviceList.py
+++ b/blueman/gui/DeviceList.py
@@ -237,6 +237,10 @@ class DeviceList(GenericList):
 
         try:
             self.Adapter = self.manager.get_adapter(adapter)
+            # The patern may be incorrect (ie removed adapter), see #590
+            if self.Adapter is None:
+                self.Adapter = self.manager.get_adapter()
+
             self.Adapter.connect_signal('property-changed', self._on_property_changed)
             self.manager.connect_signal('device-created', self._on_device_created)
             self.manager.connect_signal('device-removed', self._on_device_removed)
```

**Comment by infirit** [comment]
9a7d65efe4f2c327d8f8296cb4262894621721ab
