### ISSUE TITLE
Failed to apply network settings

### ISSUE THREAD

**Issue by ralfluederitz** [blueman-project/blueman#711]
You might not be able to connect to the Bluetooth network via this machine

g-io-error-quark: GDBus.Error:org.freedesktop.DBus.Python.GLib.Error: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/local/lib/python2.7/dist-packages/blueman/main/DbusService.py", line 38, in wrapper
    return method(*args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/blueman/plugins/mechanism/Network.py", line 56, in ReloadNetwork
    self.confirm_authorization(caller, "org.blueman.network.setup")
  File "/usr/local/libexec/blueman-mechanism", line 174, in confirm_authorization
    action_id, {}, 1, "")
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gio.py", line 171, in __call__
    None)
Error: g-io-error-quark: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Action org.blueman.network.setup is not registered (36)
 (36)

**Comment by infirit** [comment]
The error suggests you have have an old policy file installed. Make sure that [org.blueman.policy](https://github.com/blueman-project/blueman/blob/master/data/configs/org.blueman.policy.in) is in sync with rest of blueman.
