### ISSUE TITLE
Problem with PAN Setup

### ISSUE THREAD

**Issue by timmmerlan** [blueman-project/blueman#814]
blueman: 2.0.4
BlueZ: 5.46
Distribution:
Desktop environment: Ubuntu 17.10

Hi all,
I am having trouble setting up a Network Access Point with a custom IP address. I am using DHCP Server type dnsmasq and NetworkManager for PAN and DUN. When I try to apply the settings, I always get the following "Failed to apply network settings" error message:

```
org.freedesktop.DBus.Python.FileNotFoundError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/blueman/main/DbusService.py", line 36, in wrapper
    return method(*args[1:], **kwargs)
  File "/usr/lib/python3/dist-packages/blueman/plugins/mechanism/Network.py", line 59, in EnableNetwork
    nc.apply_settings()
  File "/usr/lib/python3/dist-packages/blueman/main/NetConf.py", line 318, in apply_settings
    ret = call(["ifconfig", "pan1", ip_str, "netmask", mask_str, "up"])
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ifconfig': 'ifconfig'
```
Thank you for your help!

**Comment by infirit** [comment]
Try to install ``net-tools`` which should contain the ``ifconfig`` command.
