### ISSUE TITLE
Resource Not Ready...

### ISSUE THREAD

**Issue by railsonnn** [blueman-project/blueman#824]
blueman:
BlueZ:
Distribution:
Desktop environment:

Resource Not Ready
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/blueman/bluez/errors.py", line 146, in warp
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/blueman/bluez/Adapter.py", line 135, in start_discovery
    self.get_interface().StartDiscovery()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.bluez.Error.NotReady: Resource Not Ready

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/blueman-manager", line 210, in inquiry
    self.List.DiscoverDevices()
  File "/usr/lib/python3/dist-packages/blueman/gui/DeviceList.py", line 401, in DiscoverDevices
    self.Adapter.start_discovery()
  File "/usr/lib/python3/dist-packages/blueman/bluez/errors.py", line 148, in warp
    raise parse_dbus_error(exception)
blueman.bluez.errors.DBusNotReadyError: Resource Not Ready

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

> ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

**Comment by infirit** [comment]
The adapter probably was not powered up properly but we really need to see the log from blueman-applet to debug this. See https://github.com/blueman-project/blueman/wiki/Troubleshooting#debugging
