### ISSUE TITLE
Failed to apply network setting

### ISSUE THREAD

**Issue by aacco** [blueman-project/blueman#863]
blueman:2.0.5-1
BlueZ:5.49-3
Distribution:Arch linux
Desktop environment:mate

When I turn NAP on at Local Services window, I got this error:
org.freedesktop.DBus.Python.FileNotFoundError: Traceback (most recent call last):
  File "/lib/python3.6/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/lib/python3.6/site-packages/blueman/main/DbusService.py", line 36, in wrapper
    return method(*args[1:], **kwargs)
  File "/lib/python3.6/site-packages/blueman/plugins/mechanism/Network.py", line 59, in EnableNetwork
    nc.apply_settings()
  File "/lib/python3.6/site-packages/blueman/main/NetConf.py", line 311, in apply_settings
    ret = call(["ifconfig", "pan1", ip_str, "netmask", mask_str, "up"])
  File "/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ifconfig': 'ifconfig'

Please tell me what to do(such as where I can download above files...)
Thank you

* [ ] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

> ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

**Comment by cschramm** [comment]
The 2.0 versions require the `ifconfig` utility from net-tools. The current master also supports the `ip` command from iproute2.

**Comment by aacco** [comment]
I installed net-tools and retried, then I got:
org.freedesktop.DBus.Python.FileNotFoundError: Traceback (most recent call last):
  File "/lib/python3.6/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/lib/python3.6/site-packages/blueman/main/DbusService.py", line 36, in wrapper
    return method(*args[1:], **kwargs)
  File "/lib/python3.6/site-packages/blueman/plugins/mechanism/Network.py", line 59, in EnableNetwork
    nc.apply_settings()
  File "/lib/python3.6/site-packages/blueman/main/NetConf.py", line 326, in apply_settings
    self.dhcp_handler.do_apply()
  File "/lib/python3.6/site-packages/blueman/main/NetConf.py", line 152, in do_apply
    self.do_remove()
  File "/lib/python3.6/site-packages/blueman/main/NetConf.py", line 181, in do_remove
    dhcp_config, existing_subnet = self._read_dhcp_config()
  File "/lib/python3.6/site-packages/blueman/main/NetConf.py", line 92, in _read_dhcp_config
    f = open(DHCP_CONFIG_FILE, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/etc/dhcp3/dhcpd.conf'

``dhcp3`` means ``dhcp3-server``?
What should I install for this?

**Comment by infirit** [comment]
@aacco you have to configure blueman via ``blueman-services`` which dhcp server to use. Arch has dnsmasq in its optdepend and the recommended by us.

@City-busz it appears net-tools is missing in the pkgbuild or would this get added by installing dnsmasq?

**Comment by cschramm** [comment]
@City-busz: That pass is configurable (`--with-dhcp-config=PATH`).

**Comment by infirit** [comment]
@City-busz I'll update the list of dependencies. For 2.1 I'll see if networkmanager can handle this and add support for it. And improve the error message as it is not very useful like this. But for now please can you add net-tools :smiley:

**Comment by aacco** [comment]
Thank you for your helps! Conecting ev3 succeeded!

**Comment by aacco** [comment]
close
