### ISSUE TITLE
PPPSupport times out on a dbus call

### ISSUE THREAD

**Issue by infirit** [blueman-project/blueman#906]
With my N900 I have DUN support but it appears something is holding up the dbus call and we timeout.

**Comment by infirit** [comment]
Bytes vs codepoints :scream: 
```
blueman-mechanism 10.50.43 DEBUG    blueman-mechanism:170 confirm_authorization: (True, False, {})
blueman-mechanism 10.50.43 INFO     PPPConnection:179 send_command: --> ATZ E0 V1 X4 &C1 +FCLASS=0
blueman-mechanism 10.50.44 ERROR    blueman-mechanism:46 write     : Traceback (most recent call last):
blueman-mechanism 10.50.44 ERROR    blueman-mechanism:46 write     :   File "/usr/lib64/python3.6/site-packages/gi/overrides/GLib.py", line 748, in <lambda>
blueman-mechanism 10.50.44 ERROR    blueman-mechanism:46 write     : func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
blueman-mechanism 10.50.44 ERROR    blueman-mechanism:46 write     :   File "/usr/lib64/python3.6/site-packages/blueman/main/PPPConnection.py", line 190, in on_data_ready
blueman-mechanism 10.50.44 ERROR    blueman-mechanism:46 write     : self.buffer += os.read(self.file, 1)
blueman-mechanism 10.50.44 ERROR    blueman-mechanism:46 write     : TypeError
blueman-mechanism 10.50.44 ERROR    blueman-mechanism:46 write     : :
blueman-mechanism 10.50.44 ERROR    blueman-mechanism:46 write     : must be str, not bytes
blueman-mechanism 10.50.58 ERROR    blueman-mechanism:46 write     : /usr/lib64/python3.6/site-packages/blueman/main/PPPConnection.py:223: Warning: Source ID 15 was not found when attempting to remove it
blueman-mechanism 10.50.58 ERROR    blueman-mechanism:46 write     :   GLib.source_remove(self.io_watch)
```
