### ISSUE TITLE
Unhide func failing in BluemanServices

### ISSUE THREAD

**Issue by infirit** [blueman-project/blueman#921]
Got the below but no time to investigate right now. Have not tried to replicate.

```python
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/gi/overrides/Gtk.py", line 1593, in main_quit
    @override(Gtk.main_quit)
  File "/home/sander/repos/blueman/blueman/Functions.py", line 272, in handler
    unhide_func(event_time)
  File "/home/sander/repos/blueman/blueman/main/Services.py", line 50, in <lambda>
    check_single_instance("blueman-services", lambda time: self.Dialog.present_with_time(time))
AttributeError: 'BluemanServices' object has no attribute 'Dialog'
```

**Comment by infirit** [comment]
I haven't seen this in a long time so closing.
