### ISSUE TITLE
blueman-manager won't start after update

### ISSUE THREAD

**Issue by jeanschneider** [blueman-project/blueman#987]
blueman: 2.0.7-1 (stable/manjaro repo)
BlueZ: 5.50-3
Distribution: Manjaro
Desktop environment: xfce4

Error code when launching blueman-manager : 
```
[jeans@HP_x360 ~]$ blueman-manager

(blueman-manager:2381): Gtk-WARNING **: 10:14:35.776: Theme parsing error: gtk.css:63:28: The :prelight pseudo-class is deprecated. Use :hover instead.

(blueman-manager:2381): Gtk-WARNING **: 10:14:35.776: Theme parsing error: gtk.css:73:35: The :prelight pseudo-class is deprecated. Use :hover instead.
_________
Load (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:60)
['Services', 'PulseAudioProfile'] 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.manager.Services.Services'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.manager.PulseAudioProfile.PulseAudioProfile'> 
_________
pa_context_event (/usr/lib/python3.7/site-packages/blueman/main/PulseAudioUtils.py:341)
1 
/usr/bin/blueman-manager:67: DeprecationWarning: Gtk.Window.get_has_resize_grip is deprecated
  if self.window.get_has_resize_grip():
blueman-manager version 2.0.7 starting
Stale PID, overwriting
_________
pa_context_event (/usr/lib/python3.7/site-packages/blueman/main/PulseAudioUtils.py:341)
2 
_________
on_bluez_name_owner_changed (/usr/bin/blueman-manager:96)
org.bluez owner changed to  :1.2 
_________
get_interface_version (/usr/lib/python3.7/site-packages/blueman/bluez/BlueZInterface.py:13)
Detected BlueZ 5 
_________
SetAdapter (/usr/lib/python3.7/site-packages/blueman/gui/DeviceList.py:271)
 
_________
on_adapter_changed (/usr/lib/python3.7/site-packages/blueman/gui/manager/ManagerToolbar.py:83)
toolbar adapter /org/bluez/hci0 
_________
__init__ (/usr/lib/python3.7/site-packages/blueman/main/Device.py:26)
caching initial properties 
_________
add_device (/usr/lib/python3.7/site-packages/blueman/gui/DeviceList.py:317)
adding new device 
_________
do_cache (/usr/lib/python3.7/site-packages/blueman/gui/DeviceList.py:496)
Caching new device 48:D6:D5:98:2C:A5 
_________
row_update_event (/usr/lib/python3.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:275)
row update event Fake False 
_________
row_update_event (/usr/lib/python3.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:275)
row update event Trusted 0 
_________
row_update_event (/usr/lib/python3.7/site-packages/blueman/gui/manager/ManagerDeviceList.py:275)
row update event Paired 1 
_________
__init__ (/usr/lib/python3.7/site-packages/blueman/main/Device.py:26)
caching initial properties 
_________
add_device (/usr/lib/python3.7/site-packages/blueman/gui/DeviceList.py:317)
adding new device 
_________
do_cache (/usr/lib/python3.7/site-packages/blueman/gui/DeviceList.py:496)
Caching new device 88:C6:26:EC:DD:D5 
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dbus/connection.py", line 604, in msg_reply_handler
    reply_handler(*message.get_args_list(**get_args_opts))
  File "/usr/bin/blueman-manager", line 150, in on_bluez_name_owner_changed
    self.List.DisplayKnownDevices(autoselect=True)
  File "/usr/lib/python3.7/site-packages/blueman/gui/DeviceList.py", line 392, in DisplayKnownDevices
    self.device_add_event(Device(device))
  File "/usr/lib/python3.7/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 207, in device_add_event
    self.AppendDevice(device)
  File "/usr/lib/python3.7/site-packages/blueman/gui/DeviceList.py", line 425, in AppendDevice
    self.add_device(device, True)
  File "/usr/lib/python3.7/site-packages/blueman/gui/DeviceList.py", line 332, in add_device
    self.row_setup_event(iter, device)
  File "/usr/lib/python3.7/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 253, in row_setup_event
    description = get_major_class(device.Class).capitalize()
  File "/usr/lib/python3.7/site-packages/blueman/DeviceClass.py", line 239, in get_major_class
    index = (klass >> 8) & 0x1F
TypeError: unsupported operand type(s) for >>: 'str' and 'int'
_________
pa_context_event (/usr/lib/python3.7/site-packages/blueman/main/PulseAudioUtils.py:341)
3 
_________
pa_context_event (/usr/lib/python3.7/site-packages/blueman/main/PulseAudioUtils.py:341)
4 
_________
on_pa_ready (/usr/lib/python3.7/site-packages/blueman/plugins/manager/PulseAudioProfile.py:29)
connected 
_________
<lambda> (/usr/lib/python3.7/site-packages/blueman/main/PulseAudioUtils.py:353)
1 

```
When launching it from blueman-applet (same...):

```
[jeans@HP_x360 ~]$ blueman-applet

(blueman-applet:1944): Gtk-WARNING **: 10:07:20.572: Theme parsing error: gtk.css:63:28: The :prelight pseudo-class is deprecated. Use :hover instead.

(blueman-applet:1944): Gtk-WARNING **: 10:07:20.572: Theme parsing error: gtk.css:73:35: The :prelight pseudo-class is deprecated. Use :hover instead.
blueman-applet version 2.0.7 starting
Stale PID, overwriting
_________
Load (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:60)
['NMPANSupport', 'TransferService', 'Menu', 'AuthAgent', 'DhcpClient', 'RecentConns', 'StatusIcon', 'SerialManager', 'StandardItems', 'Headset', 'DiscvManager', 'PowerManager', 'AppIndicator', 'Networking', 'DBusService', 'NMDUNSupport', 'KillSwitch', 'ExitItem', 'NetUsage', 'ShowConnected', 'PPPSupport', 'GameControllerWakelock'] 
_________
get_interface_version (/usr/lib/python3.7/site-packages/blueman/bluez/BlueZInterface.py:13)
Detected BlueZ 5 
_________
Load (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:60)
Unable to load plugin module AppIndicator
cannot import name AppIndicator3, introspection typelib not found 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.StatusIcon.StatusIcon'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.DBusService.DBusService'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.NMPANSupport.NMPANSupport'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.TransferService.TransferService'> 
_________
get_interface_version (/usr/lib/python3.7/site-packages/blueman/bluez/obex/Base.py:20)
Detected BlueZ integrated obexd 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.Menu.Menu'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.AuthAgent.AuthAgent'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
Not loading DhcpClient because it's conflict has higher priority 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.RecentConns.RecentConns'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.SerialManager.SerialManager'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.StandardItems.StandardItems'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.Headset.Headset'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.DiscvManager.DiscvManager'> 
_________
update_menuitems (/usr/lib/python3.7/site-packages/blueman/plugins/applet/DiscvManager.py:123)
warning: Adapter is None 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.PowerManager.PowerManager'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.Networking.Networking'> 
_________
load_nap_settings (/usr/lib/python3.7/site-packages/blueman/plugins/applet/Networking.py:36)
Loading NAP settings 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.NMDUNSupport.NMDUNSupport'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.KillSwitch.KillSwitch'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.ExitItem.ExitItem'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.ShowConnected.ShowConnected'> 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
Not loading PPPSupport because it's conflict has higher priority 
_________
__load_plugin (/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py:133)
loading <class 'blueman.plugins.applet.GameControllerWakelock.GameControllerWakelock'> 
_________
io_event (/usr/lib/python3.7/site-packages/blueman/plugins/applet/KillSwitch.py:71)
killswitch registered 1 
_________
io_event (/usr/lib/python3.7/site-packages/blueman/plugins/applet/KillSwitch.py:71)
State: True 
_________
UpdatePowerState (/usr/lib/python3.7/site-packages/blueman/plugins/applet/PowerManager.py:159)
off False 
foff False 
on True 
current state True 
new state True 
_________
_on_obex_owner_changed (/usr/lib/python3.7/site-packages/blueman/plugins/applet/TransferService.py:172)
obex owner changed: :1.61 
_________
on_dbus_name_owner_change (/usr/bin/blueman-applet:95)
org.bluez owner changed to :1.2 
_________
register_agent (/usr/lib/python3.7/site-packages/blueman/plugins/applet/AuthAgent.py:63)
Registering agent 
_________
initialize (/usr/lib/python3.7/site-packages/blueman/plugins/applet/RecentConns.py:144)
rebuilding menu 
_________
set_nap (/usr/lib/python3.7/site-packages/blueman/plugins/applet/Networking.py:65)
set nap False 
_________
enumerate_connections (/usr/lib/python3.7/site-packages/blueman/plugins/applet/ShowConnected.py:53)
Found 0 existing connections 
_________
on_registered (/usr/lib/python3.7/site-packages/blueman/bluez/obex/AgentManager.py:18)
/org/blueman/obex_agent 

(blueman-applet:1944): Gdk-CRITICAL **: 10:07:20.776: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
_________
RequestPowerState (/usr/lib/python3.7/site-packages/blueman/plugins/applet/PowerManager.py:131)
Requesting True 
_________
on_power_state_change_requested (/usr/lib/python3.7/site-packages/blueman/plugins/applet/KillSwitch.py:118)
True 
_________
UpdatePowerState (/usr/lib/python3.7/site-packages/blueman/plugins/applet/PowerManager.py:159)
off False 
foff False 
on True 
current state True 
new state True 
_________
check (/usr/lib/python3.7/site-packages/blueman/plugins/applet/PowerManager.py:119)
callbacks done 
_________
set_adapter_state (/usr/lib/python3.7/site-packages/blueman/plugins/applet/PowerManager.py:90)
True 

(blueman-manager:1953): Gtk-WARNING **: 10:07:44.480: Theme parsing error: gtk.css:63:28: The :prelight pseudo-class is deprecated. Use :hover instead.

(blueman-manager:1953): Gtk-WARNING **: 10:07:44.480: Theme parsing error: gtk.css:73:35: The :prelight pseudo-class is deprecated. Use :hover instead.
/usr/bin/blueman-manager:67: DeprecationWarning: Gtk.Window.get_has_resize_grip is deprecated
  if self.window.get_has_resize_grip():
blueman-manager version 2.0.7 starting
Stale PID, overwriting
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dbus/connection.py", line 604, in msg_reply_handler
    reply_handler(*message.get_args_list(**get_args_opts))
  File "/usr/bin/blueman-manager", line 150, in on_bluez_name_owner_changed
    self.List.DisplayKnownDevices(autoselect=True)
  File "/usr/lib/python3.7/site-packages/blueman/gui/DeviceList.py", line 392, in DisplayKnownDevices
    self.device_add_event(Device(device))
  File "/usr/lib/python3.7/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 207, in device_add_event
    self.AppendDevice(device)
  File "/usr/lib/python3.7/site-packages/blueman/gui/DeviceList.py", line 425, in AppendDevice
    self.add_device(device, True)
  File "/usr/lib/python3.7/site-packages/blueman/gui/DeviceList.py", line 332, in add_device
    self.row_setup_event(iter, device)
  File "/usr/lib/python3.7/site-packages/blueman/gui/manager/ManagerDeviceList.py", line 253, in row_setup_event
    description = get_major_class(device.Class).capitalize()
  File "/usr/lib/python3.7/site-packages/blueman/DeviceClass.py", line 239, in get_major_class
    index = (klass >> 8) & 0x1F
TypeError: unsupported operand type(s) for >>: 'str' and 'int'


```

Thanks !

**Comment by infirit** [comment]
Yes, this was a bug I introduced in 2.0.7. A new release. 2.0.8, was done for this so use that or apply ad7a67d3d528c232d41ae31554f9fc70c28839e2 yourself.

Closing but feel free to continue the discussion :smile:

**Comment by jeanschneider** [comment]
Thanks ! I hope the new version will soon be on the repos !
